# Generated by Django 3.1 on 2020-09-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='delay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
