# Generated by Django 3.1 on 2020-09-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_emails', '0002_emaillist_delay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillist',
            old_name='email',
            new_name='message',
        ),
    ]
